backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/photos/George-gbrs"
public_folder: "src/assets/images"
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "agricultural",
              "industrial",
              "recladding",
              "groundworks",
              "new-build",
            ],
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Gallery Images",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Order", name: "order", widget: "number", default: 100 }
